### ISSUE TITLE
How to create dist folder?

### ISSUE THREAD

**Issue by BensenHsu** [editor-js/marker#42]
Hi @talyguryn @neSpecc , when I npm installed the tool in my own Typescript project, it will create the dist folder automatically (screenshot below). But when I pull the repository to my local and use `yarn build` or `npm install`, `npm run build`. The dist folder won't be created. Why?
<img width="190" alt="image" src="https://user-images.githubusercontent.com/51500098/210945006-c7340187-2b5f-4109-873c-f394a15c8d24.png">

**Comment by talyguryn** [comment]
`dist` folder contains the complete bundle of the app. it generated by `build` command — `yarn build` for example.

this folder is ignored by git because it is irrelevant to the source code and can be generated again. it is created during development for local testing or just before publishing to npm. there is no source code in npm, only readme, license, types and list folder.

**Comment by BensenHsu** [comment]
> `dist` folder contains the complete bundle of the app. it generated by `build` command — `yarn build` for example.
> 
> this folder is ignored by git because it is irrelevant to the source code and can be generated again. it is created during development for local testing or just before publishing to npm. there is no source code in npm, only readme, license, types and list folder.

Thank you for your reply! But I cannot generate it when I'm testing it locally. Maybe I used the wrong command. Could you please share the command you use?
